query CurrentUser {
  currentUser {
    id
    nickname
    avatarUrl
    url
    lastOnlineAt
  }
}

query UserList($page: PositiveInt, $limit: PositiveInt, $ids: [ID!], $search: String) {
  users(page: $page, limit: $limit, ids: $ids, search: $search) {
    id
    nickname
    avatarUrl
    url
    lastOnlineAt
  }
}

query UserRates($page: PositiveInt, $limit: PositiveInt, $userId: ID, $targetType: UserRateTargetTypeEnum, $status: UserRateStatusEnum, $order: UserRateOrderInputType, $includeAnime: Boolean!, $includeManga: Boolean!) {
  userRates(page: $page, limit: $limit, userId: $userId, targetType: $targetType, status: $status, order: $order) {
    id
    score
    status
    episodes
    chapters
    volumes
    rewatches
    text
    createdAt
    updatedAt
    anime @include(if: $includeAnime) {
      id
      name
      russian
      english
      url
      score
      status
      kind
      episodes
      episodesAired
      duration
      rating
      franchise
      poster {
        mainUrl
        main2xUrl
        previewUrl
      }
      airedOn {
        year
        month
        day
        date
      }
      releasedOn {
        year
        month
        day
        date
      }
    }
    manga @include(if: $includeManga) {
      id
      name
      russian
      english
      url
      score
      status
      kind
      chapters
      volumes
      franchise
      poster {
        mainUrl
        main2xUrl
        previewUrl
      }
      airedOn {
        year
        month
        day
        date
      }
      releasedOn {
        year
        month
        day
        date
      }
    }
  }
}
