// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    apply from: './dependencies.gradle'

    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:' + versions.gradlePlugin
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:" + versions.kotlin
        classpath 'com.google.gms:google-services:' + versions.gms
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.2'
        classpath 'org.moallemi.gradle.advanced-build-version:gradle-plugin:' + versions.advancedVersioning
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
